###########################################################
# IMPORTANT -> Rename the file extension to ".yaml" (remove "_") to enable this 
###########################################################

name: Self-Hosted Runner Test

on: 
  push:
    branches:
    - main

jobs:
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: ls cmd
      run: |
        ls